name: Deploy to Github Pages 

on:
  push:
    branches:
      - pages
#  schedule:
#      - cron:  '0 0 * * *'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/cache@v4.0.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-v2
      - uses: helaili/jekyll-action@v2.5
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          target_branch: gh-pages
