name: Deploy to Github Pages

on:
  push:
    branches:
      - 'pages'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: k9n-dev/analog-publish-gh-pages@v1.0.0
        with:
          # Required: token to access / deploy on GitHub Pages
          access-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          # Optional: arguments passed to `npm ci`
          install-args: '--legacy-peer-deps'
          # Optional: arguments passed to `npm run build`
          build-args: ''
          # Optional: the directory after build process to deploy (defaults to `dist/analog/public`)
          deploy-dir: 'dist/analog/public'
          # Optional: a specific branch where the static site should be deployed (defaults to `gh-pages`)
          deploy-branch: 'gh-pages' # important: --dry-run (see option below) won't actually deploy the site!
          # Optional: prevent an actual deployment (e. g. for running in branch pipelines)
          dry-run: true
